# Site settings
title: Interactivos?'16
description: Água e Autonomia

baseurl: "/doc.interactivos16.info"
url: "https://interactivos16.github.io"
permalink: /:year/:month/:day/:title/

#########################################

# Build settings
markdown: kramdown
port: 4444
