# Site settings
title: Interactivos?'16
description: Água e Autonomia

baseurl: "/blog-test00/"
url: "https://thiagohersan.github.io/blog-test00/"
permalink: /:year/:month/:day/:title/

#########################################

# Build settings
markdown: kramdown
port: 4444
