# Site settings
title: Interactivos?'16
description: Água e Autonomia

baseurl: "/doc.interactivos16"
url: "https://associacaosilo.github.io"
permalink: /:year/:month/:day/:title/

#########################################

# Build settings
markdown: kramdown
port: 4455
