# Site settings
title: Interactivos?'16
description: Água e Autonomia

baseurl: "doc.interactivos16.info"
url: "//doc.interactivos16.info"
permalink: /:year/:month/:day/:title/

#########################################

# Build settings
markdown: kramdown
port: 4455
